services:
  postgres:
    image: postgres:16-alpine
    container_name: vaultpay-postgres
    environment:
      POSTGRES_USER: vaultpay_user
      POSTGRES_PASSWORD: vaultpay_password
      POSTGRES_DB: vaultpay
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaultpay_user -d vaultpay"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vaultpay-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # NEW: Jaeger Tracing UI and Collector
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: vaultpay-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true # <-- THIS UNLOCKS THE TELEMETRY DOOR
    ports:
      - "16686:16686"
      - "4318:4318"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vaultpay-api:v1
    container_name: vaultpay-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://vaultpay_user:vaultpay_password@postgres:5432/vaultpay?sslmode=disable
      - REDIS_ADDR=redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318 # NEW: Tells Go where to send trace data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger:
        condition: service_started
  prometheus:
    image: prom/prometheus:latest
    container_name: vaultpay-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: vaultpay-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password for our local dashboard
    depends_on:
      - prometheus