name: VaultPay CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26' # Matching your local and Docker version

    - name: Verify Dependencies
      run: go mod verify

    - name: Run Test Suite
      run: go test ./... -v -cover

    - name: Test Docker Build
      run: docker build -t vaultpay-api:test .